### ISSUE TITLE
powertop issues with i226

### ISSUE THREAD

**Issue by decommentator** [fenrus75/powertop#143]
when having multiple i226 integrated in one box I see the following strange behaviour

clean install with proxmox
PowerTOP version 2.14
running powertop no problem everything works as should be

running powertop --auto-tune
afterwards:
not possible to run powertop anymore 
not possible to reboot

**Comment by tomillr** [comment]
I can confirm this issue when running "powertop --auto-tune" on an Odroid H4+ board which use two Intel I226-V network ports.

[Odroid H4 hardware specification](https://wiki.odroid.com/odroid-h4/hardware)

**Comment by fenrus75** [comment]
this is a device driver bug... it fails when turning on power management

**Comment by tomillr** [comment]
Thanks for your assessment. 
I'm currently running Ubuntu Server 24.04. with just the basic kernel drivers. Is there maybe a proprietary Intel driver that properly supports power management?

**Comment by fenrus75** [comment]
Intel doesn't do proprietary drivers... but you can file a bug against the
driver at bugzilla.kernel.org and it'll get to the maintainers

**Comment by tomillr** [comment]
How about this driver for the I226-V from the official Intel website?

https://www.intel.com/content/www/us/en/download/15084/intel-ethernet-adapter-complete-driver-pack.html

**Comment by tomillr** [comment]
@fenrus75 
Could you maybe chime in over at Bugzilla? You're input surely carries more weight and might help to get this bug fixed.

https://bugzilla.kernel.org/show_bug.cgi?id=218499

**Comment by popy2k14** [comment]
Kernel 6.12 (new LTS) dropped a few months back.
I read somewhere that the issue was solved around ~6.11 kernel.

Can anyone of you please confirm the issue is solved in 6.12?

**Comment by tomillr** [comment]
> Can anyone of you please confirm the issue is solved in 6.12?

I can confirm that the problem seems to have been fixed with Kernel 6.11 (tested with Ubuntu Server 24.10).

**Comment by popy2k14** [comment]
thx for confirming!

Will get an I226-V now for my Unraid server and hopes it runs stable with ASPM (power savings turned on) and i can reach higher c-states without the need to disable ASPM.

Will report back here after i have tested it.

**Comment by popy2k14** [comment]
I have now tested the I226-V in an Gigabyte H610i Mainboard with the latest F33 BIOS.
Had to disable "Plattform Power Management -> PEG ASPM" (giving up all cpu pkg c states) to disable ASPM fo the card to get it stable.

With "PEG ASPM" enabled (ASPM enabled for the NIC card) it was functioning and not freeze the system (so above issue seems to be solved), but the speed was dropping under 100 Mbits/s often. Also SMB file transfer to unraid was very unstable!

Maybe ill try an I226-T1 again.

**Comment by Herve-M** [comment]
> > Can anyone of you please confirm the issue is solved in 6.12?
> 
> I can confirm that the problem seems to have been fixed with Kernel 6.11 (tested with Ubuntu Server 24.10 running on a Odroid H4+).

Which version of kernel are you using? My Ubuntu Server 24.04  using `6.11.0-29-generic` still have the problem.

**Comment by popy2k14** [comment]
I am on kernel 6.12.4 (latest Unraid 7.1.4) and the issue is still there. Currently disabled ASPM for the card to keep bandwidth up. Sadly this drives up power consumption a little bit.

**Comment by meminens** [comment]
I am on `6.16.8-arch3-1` and the issue is still present. Any workarounds?

**Comment by popy2k14** [comment]
My workaround hasn't changed, i disabled ASPM for the card to keep bandwidth up.

**Comment by meminens** [comment]
Thanks. I am doing the same. I was wondering if there is a fix for this NIC so that we can enable ASPM without any issues.

**Comment by popy2k14** [comment]
Sadly i am not aware of one.
I wand also enable "PEG ASPM"...
It seems an issue with the card/firmware itself and not linux related, see here some windows users on an NUC with the same NIC: https://www.reddit.com/r/intelnuc/comments/1951rgk/very_slow_speeds_with_i226v_on_intel_nuc13anbi5/

Dont know (or maybe) there is an updateable firmware on the card?
Here is an interessting thread about NVM flashing: https://forum.opnsense.org/index.php?topic=48695.0
And the ASPM issue: https://forum.opnsense.org/index.php?topic=48777.0

P.S.: i have posted our issue in the ASPm thread: https://forum.opnsense.org/index.php?msg=248507

**Comment by meminens** [comment]
I wish I could understand half the conversation in the opensense forums. Looks like there is a GitHub repo with .bin files. But I am not sure how to install those.

**Comment by popy2k14** [comment]
They are talking about flasing/updating the firmware/config of the card in the first thread.
In the second thread they want to disable ASPM suppport of the card, the oposite what we want.
I have asked in the thread, let's see if they answer and maybe can help us.

**Comment by popy2k14** [comment]
Update.
I updated my I226-V card from NVM 2.13 to 2.32 and the issue is not solved.
See post #117: https://forum.opnsense.org/index.php?topic=48695.117
